version: '3'

services:
    db:
      image: postgres:14.1-alpine
      container_name: db
      restart: unless-stopped
      expose:
        - 5432
      environment:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: dbuser
          POSTGRES_PASSWORD: test
          POSTGRES_SERVER: db
          POSTGRES_DB_PORT: 5432
          POSTGRES_DB: db
      healthcheck:
          test: pg_isready -U dbuser -d db

    teamwork:
      restart: always
      build: ./
      ports:
      - "8080:8080"
      depends_on:
        - db
      env_file:
        - .env