"""add_mentor

Revision ID: 00b78fbecc85
Revises: 41fb567e4a7b
Create Date: 2024-03-13 18:06:16.736073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b78fbecc85'
down_revision = '41fb567e4a7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentors',
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=64), nullable=True),
    sa.Column('telegram_link', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('education', sa.Enum('HIGHER_EDUCATION', 'SPECIALIZED_SECONDARY', 'SECONDARY', name='education'), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('_password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_mentors_id'), 'mentors', ['id'], unique=False)
    op.add_column('directions', sa.Column('mentor_id', sa.Integer(), nullable=True))
    op.drop_constraint('directions_user_id_fkey', 'directions', type_='foreignkey')
    op.create_foreign_key(None, 'directions', 'mentors', ['mentor_id'], ['id'], ondelete='CASCADE')
    op.drop_column('directions', 'user_id')
    op.add_column('experience', sa.Column('mentor_id', sa.Integer(), nullable=True))
    op.drop_constraint('experience_user_id_fkey', 'experience', type_='foreignkey')
    op.create_foreign_key(None, 'experience', 'mentors', ['mentor_id'], ['id'], ondelete='CASCADE')
    op.drop_column('experience', 'user_id')
    op.drop_column('users', 'is_mentor')
    op.drop_column('users', 'time_he_can_spend')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('time_he_can_spend', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_mentor', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('experience', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'experience', type_='foreignkey')
    op.create_foreign_key('experience_user_id_fkey', 'experience', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('experience', 'mentor_id')
    op.add_column('directions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'directions', type_='foreignkey')
    op.create_foreign_key('directions_user_id_fkey', 'directions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('directions', 'mentor_id')
    op.drop_index(op.f('ix_mentors_id'), table_name='mentors')
    op.drop_table('mentors')
    # ### end Alembic commands ###
