"""added_column_likedby_for_user_model

Revision ID: 32b2bfc3ad33
Revises: 02f19fd2ffab
Create Date: 2024-03-19 18:40:11.275872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32b2bfc3ad33'
down_revision = '02f19fd2ffab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('liked_by', postgresql.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'liked_by')
    # ### end Alembic commands ###
