"""add_blocklist_table

Revision ID: 41fb567e4a7b
Revises: e078f5541efd
Create Date: 2024-03-12 17:01:18.875913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41fb567e4a7b'
down_revision = 'e078f5541efd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokenblocklist',
    sa.Column('jti', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokenblocklist_id'), 'tokenblocklist', ['id'], unique=False)
    op.create_index(op.f('ix_tokenblocklist_jti'), 'tokenblocklist', ['jti'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokenblocklist_jti'), table_name='tokenblocklist')
    op.drop_index(op.f('ix_tokenblocklist_id'), table_name='tokenblocklist')
    op.drop_table('tokenblocklist')
    # ### end Alembic commands ###
