"""added_course

Revision ID: dbdc49011c80
Revises: fa5d1378e8fe
Create Date: 2024-03-16 05:00:59.186363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbdc49011c80'
down_revision = 'fa5d1378e8fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
