"""added_profile

Revision ID: fa5d1378e8fe
Revises: 00b78fbecc85
Create Date: 2024-03-14 01:59:07.004141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa5d1378e8fe'
down_revision = '00b78fbecc85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_directions_id', table_name='directions')
    op.drop_table('directions')
    op.add_column('mentors', sa.Column('english_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='englishlevel'), nullable=True))
    op.add_column('mentors', sa.Column('languages', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('users', 'english_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('english_level', postgresql.ENUM('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='englishlevel'), autoincrement=False, nullable=True))
    op.drop_column('mentors', 'languages')
    op.drop_column('mentors', 'english_level')
    op.create_table('directions',
    sa.Column('speciality', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('stack', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('mentor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], name='directions_mentor_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='directions_pkey')
    )
    op.create_index('ix_directions_id', 'directions', ['id'], unique=False)
    # ### end Alembic commands ###
